version: '3.9'

services:

  typecheck:
    image: node:16.18-bullseye
    volumes:
      - "./package.json:/app/package.json:ro"
      - "./package-lock.json:/app/package-lock.json:ro"
      - "./tsconfig.json:/app/tsconfig.json:ro"
      - "./api/:/app/api:ro"
      - "./example/:/app/example:ro"
      - "./db/:/app/db:ro"
      - "./util/:/app/util:ro"
    working_dir: /app
    command: bash -c 'npm install --save=false && node_modules/.bin/tsc --watch'

  example:
    image: node:16.18-bullseye
    volumes:
      - "./package.json:/app/package.json:ro"
      - "./package-lock.json:/app/package-lock.json:ro"
      - "./tsconfig.json:/app/tsconfig.json:ro"
      - "./api/:/app/src/api:ro"
      - "./example/:/app/src/example:ro"
      - "./util/:/app/src/util:ro"
      - "./db/:/app/src/db:ro"
    working_dir: /app
    command: bash -c 'npm install --save=false && node_modules/.bin/nodemon --exec bash -c "npm run babel && npm run example"'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 6001:5432
    command: ["postgres", "-c", "log_statement=all"]
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 6002:8080
