version: '3.9'

services:

  typecheck:
    image: node:16-bullseye
    volumes:
      - "./package.json:/app/package.json:ro"
      - "./tsconfig.json:/app/tsconfig.json:ro"
      - "./api/:/app/api:ro"
    command: bash -c 'cd /app && npm install && node_modules/.bin/tsc --watch'

  example:
    image: node:16-bullseye
    volumes:
      - "./package.json:/app/package.json:ro"
      - "./tsconfig.json:/app/tsconfig.json:ro"
      - "./api/:/app/api:ro"
    command: bash -c 'cd /app && npm install && node_modules/.bin/nodemon --exec bash -c "npm run babel && npm run example"'